### ISSUE TITLE
Adding ".DS_Store" .gitignore file?

### ISSUE THREAD

**Issue by garzarobm** [umer936/umer936.com#2]
Had a quick question about the note about the .gitignore file of a recent pull request I made, please look below for quote and link to original PR.

"Also .gitignore is ignoring for ignoring the file from the repo, not for another tool to exclude the file. I don't expect you to have anything in .gitignore (I pretty much only gitignore: config/environment/ide files and libs/build files/binaries)."

_Originally posted by @umer936 in https://github.com/umer936/umer936.com/issues/1#issuecomment-2273524337_
            
So when developing with a Mac computer, one of the files that usually appears are ".DS_Store" files that contain metadata about folder contents/views, similar to temp folders generated by windows/linux (different names across different OS).

My questions are:
1. Would these metadata files fall under "config/environment/ide files and libs/build files/binaries" as stated in the comment?
2. If so, would you like the .gitignore file under a particular folder (parent/child) for placing the contents?

Feel free to provide any additional details or format from different repository as example.

**Comment by umer936** [comment]
Oh that's right. Yeah that's definitely a metadata file and so .DS_Store should not be committed. 

Just don't commit that file. 

If we had more people working on the repo, then I would say to add in a .gitignore, but it's just you and I committing here. 

For reference, this is how I make a `.gitignore` file: https://gitignore.io 

You put in all the tool/frameworks/etc names that you're using (e.g. like OSX, PHPStorm, etc) and it spits out the file.
